adfinis/timed-backend

timed/settings.py
Change JWT expiry timeouts to allow for users to stay logged in over a
longer time than previously possible. The idea with these settings is to
allow for the following use cases:
* User doesn't get logged out during daily use
* User only needs to log in once per week
* A user is still logged after a free day during the week
These timeouts where set in this fashion with usability being the
primary aim. Due to the data expected in the system more strict security
settings are not a consideration.
=> Extend JWT timeout to be less zealous

.flake8
This led to a lot of noise in the code without adding any value. Whether a comment is required needs to be reviewed in a PR on a case by case basis and cannot be done with strict rules.
=> Turning off forced requirement of docstrings

requirements.txt, timed/models.py, timed/settings.py, timed/templates/django/forms/widgets/checkbox_option.html, timed/urls.py
Jet and crispy forms do not add any more functionality but add higher complexity which makes updating of Django more difficult.
=> Remove jet and crispy forms dependency

timed/projects/filters.py, timed/projects/tests/test_task.py, timed/projects/views.py
It only counts most frequent tasks of user which have been reported to in the last few months as only those are relevant for usability. Filter expects an integer of how may tasks need to be given.
This supersedes #22.
=> Added "my_most_frequent" filter to task end point

timed/employment/admin.py
Employments, absences and overtime credits can now be configured
directly inline of the given user.
To avoid merge conflicts this is based on PR #35 so shouldn't be merged before it.
=> Improve usability of user admin view

timed/employment/admin.py
It is usually more intuitive to configure what user supervises which supervisees.
=> Add supervisee admin panel per user

timed/settings.py
Otherwise when exporting a report it would take authentication of session which is not desired.
=> JWT needs to be authenticated before django admin session

timed/employment/filters.py, timed/projects/tests/test_customer.py, timed/projects/tests/test_project.py, timed/projects/tests/test_task.py, timed/projects/views.py
Filters are added to Customer, Project, Task and User end point
to be able to filter archived and non-archived objects.
Following changes need to be made in Timed-Frontend:
* In tracking and reschedule part only active customer, projects and tasks should be shown
* In project analysis all should be shown
=> Per default end points return archived objects

setup.py, timed/tracking/permissions.py, timed/tracking/tests/test_report.py, timed/tracking/views.py
Only admin users may change verified reports as owner doesn't know whether item has already been billed.
=> Disallow changing of verified reports

timed/tracking/views.py
Makes api cleaner as ordering is predictable for humans whereas ids are not.
=> Change default ordering on ReportViewSet to date

timed/employment/models.py, timed/employment/serializers.py, timed/employment/tests/test_employment.py, timed/employment/tests/test_user.py, timed/reports/management/commands/notify_supervisors_shorttime.py, timed/tracking/factories.py, timed/tracking/models.py, timed/tracking/serializers.py, timed/tracking/tests/test_absence.py
Only current employment was taken for worktime balance calculation which led to issues in calculation when employment changed within a year. This has been solved by calculation worktime for each employment and summarizing them.
=> Worktime calculation needs to be calculated across employments

timed/tracking/serializers.py, timed/tracking/tests/test_report.py
Total hours is included in meta, only calculated on list view and across all results not just page.
=> Add total hours to reports end point

timed/tracking/serializers.py, timed/tracking/tests/test_report.py
This for example avoids a 500 error when trying to retrieve reports of a single day where nothing has been booked yet.
=> Total hours needs to be zero when there are no reports

Makefile
When tests fails coverage is inaccurate so disabling on failure it to receive quicker results on.
=> No coverage on fail

timed/projects/filters.py, timed/projects/tests/test_task.py
User is not allowed to book onto archived tasks resp. projects so they should not appear in frequently used list of tasks.
=> Do not show archived tasks in frequently used tasks

dev_requirements.txt, timed/employment/filters.py, timed/employment/models.py, timed/employment/serializers.py, timed/employment/tests/test_user.py, timed/employment/tests/test_worktime_balance.py, timed/employment/urls.py, timed/employment/views.py, timed/mixins.py, timed/redmine/tests/test_redmine_report.py, timed/reports/tests/test_notify_changed_employments.py, timed/reports/views.py, timed/tracking/models.py
Give client the ability to calculate worktime on a given date. This PR includes some minor performance improvements in the calculation as well.
User end point won't include a worktime balance anymore. This means this change is not backwards compatible and should not be merged before Frontend has not been updated.
=> Move worktime calculation into its own end point

timed/employment/filters.py, timed/employment/serializers.py, timed/employment/tests/test_worktime_balance.py, timed/employment/views.py
Only returns worktime balances of every user at the date when either a report or a absence has been reported.
=> Add last reported date filter to worktime balance

timed/reports/tests/test_work_report.py, timed/reports/views.py, timed/tracking/filters.py
`select_related` of Django Queryset joins nullable `verified_by` foreign key with `INNER JOIN` instead of `LEFT JOIN` which causes an empty result when `verified_by` is `NULL`.
=> Prefetch verified_by instead of select

pytest.ini
`make test` already forces creation of database but this changes increases
performance when running tests on local machine.
=> Reuse db when running pytest

timed/permissions.py, timed/tracking/serializers.py, timed/tracking/tests/test_report.py, timed/tracking/views.py
This removes the dependency on the is_staff flag. Instead permissions are given by role of user in terms of given project resp. user.
Whereas supervisor may change report it may not verify it as this is the responsibility of the reviewer. Superuser on the other hand may verify all reports.
=> Allow reviewer, supervisor and superuser to change reports

requirements.txt
django-json-api is currently only tested with series 3.6 so need to pin it for safety reasons.
=> Pin rest framework to 3.6 series

timed/authentication.py, timed/settings.py
Frontend doesn't require this anymore for downloads. As it is a security concern that token end up in log files it is better to remove it as not needed anymore.
=> Remove obsolete authentication through token query param

timed/employment/urls.py, timed/projects/urls.py, timed/reports/urls.py, timed/tracking/urls.py
DefaultRouter has a feature to enable root view. This only works though if a single DefaultRouter is used. This is not desired in our case so root view was not complete.
Instead of having a invalid root view it is better to remove it - hence moving to SimpleRouter.
=> Move from DefaultRouter to SimpleRouter

requirements.txt
As jsonapi is now also compatible with DRF 3.7 removed fixed dependencies.
=> Update to newest versions

.gitignore, requirements.txt, timed/employment/relations.py, timed/employment/views.py, timed/tracking/serializers.py, timed/tracking/views.py
Fixes #268
Beside some deprecation warnings main issue to fix was that read_only and default may not be used together anymore. Replaced with `CurrentUserResourceRelatedField.`
=> Update to rest framework 3.8.2

requirements.txt, timed/tracking/tests/test_attendance.py
Fixes 500 error as old django-json-api version was used where `get_queryset` was not allowed to be overwritten in `ResourceRelatedField`.
=> Allow passing on user as relationship

timed/permissions.py, timed/tracking/tests/test_activity.py, timed/tracking/views.py
Remove unnecessary activity field in reports and make activity read only if it has been transferred.
=> Add activity permission

pytest.ini
This was fixed in pytest-freezegun 0.3.0
=> Remove obsolete ignore deprecation warning

.gitignore, timed/tracking/tests/test_absence.py, timed/tracking/views.py
This commit fixes a bug where supervisees had their absences
duplicated by the number of supervisors they have.
=> Fix duplicated absences for supervisees

pytest.ini, requirements.txt, setup.py, timed/employment/views.py, timed/permissions.py, timed/tracking/views.py
Replace existing permission_classes composed using rest_condition
operator `C()` with native operators.
Introduce new Permission `IsNotDelete` as complement to `IsDeleteOnly`
because there's no negation allowed, only bitwise `&` and `|`.
Get rid of rest_condition dependency.
=> Remove rest_condition for REST framework operators

Dockerfile
I added a timout variable that could be overridden by actual deployments so we can control how long it waits for the database to be up.
Reasoning: When deploying simultaneously with Postgres, the database needs some time to be configured and reachable
=> Added timeout var for bash script

timed/settings.py, timed/tracking/tasks.py
Make fields showing up in changed reports mail configurable
Default: ["task", "comment", "not_billable"]
=> feat(tracking): configurable fields for changes mail

Dockerfile, requirements.txt
The psycopg2-bin package is intended for getting a dev setup running
quickly, but not for production use.
See: https://www.psycopg.org/docs/install.html#binary-install-from-pypi
=> chore: move to psycopg2 wheel

timed/reports/tests/test_work_report.py, timed/reports/views.py, timed/settings.py
The `WORK_REPORTS_EXPORT_MAX_COUNT` setting restricts work reports
export to the given count. This should fix cases where the (unfiltered)
queryset is too big to handle.
=> feat: add setting to restrict work reports export size

timed/locale/en/LC_MESSAGES/django.po, timed/settings.py, timed/tracking/tests/test_report.py, timed/tracking/views.py
Make sure that reports-export does not crash.
Add the settings REPORTS_EXPORT_MAX_COUNT to optionally restrict
queryset to a certain length.
Move cost_center and billing_type logic to query annotations to make it
more performant.
Return to-be-exported list a generator expression to not fill up memory.
This also includes a fix where the cost center name used the
task.project.name instead of task.cost_center.name.
=> Performance fix for reports export

timed/settings.py
Somehow it got overlooked that django-money requires the "djmoney" entry
in INSTALLED_APPS to be present. This causes the admin rendering to use
django-money specific code instead of treating the values as simple
decimals.
See: https://github.com/django-money/django-money/issues/232
=> fix(admin): use django-money as installed app

README.md, dev-config/keycloak-config.json, dev-config/nginx.conf, docker-compose.yml
Add keycloak and proxy to dev-setup.
Since we are moving to OIDC auth, we need an actual OIDC provider to
test in the local dev environment.
This commit includes all the necessary bits in the docker-compose setup
to get up and running locally.
=> feat: extend docker-compose to include proxy, keycloak

timed/reports/templates/mail/notify_reviewers_unverified.txt
Change the URL to filter only for reports that are not yet verified.
=> Only show not verified reports

requirements.txt
Reverts adfinis-sygroup/timed-backend#707
That one went in too fast
=> chore: revert updating django from 3.1.7 to 3.2

.github/workflows/test.yml, Dockerfile, Makefile, cmd.sh, docker-compose.yml, requirements.txt, timed/settings.py, timed/urls.py
~~Note that currently the url `/prometheus/metrics` requires authentication. This can be setup using a confidential client given in the documentation.~~
~~Auth-free metrics is out of scope for the moment.~~
Edit: disregard above note, metrics can be scrapped from `/prometheus/metrics` without authentication.
=> feat: export metrics with django-prometheus

README.md, cmd.sh, requirements.txt, timed/settings.py
Also, use 8 workers by default instead of 4.
This is partly experimental, and partly due to us having tons of performance problems on prod, which could very well be due to the poor UWSGI config.
=> fix(runtime): use gunicorn instead of uwsgi

timed/urls.py
This is against django best practices, but this is mainly a DRF application,
and the only static files we serve are for the Django-Admin, with a limited
user base. Thus, we can serve static files without too much negative impact
=> feat(deployment): serve static files

timed/projects/migrations/0012_migrate_reviewers_to_assignees.py
Until the introduction of assignees, a reviewer could verify
reports and manage tasks of a project. Now, this has changed and
tasks can only be managed by assignees who have the manager role.
=> fix(projects): add manager role to project assignees

requirements.txt, timed/settings.py, timed/urls.py
- Use whitenoise to host static files.
Fixes #776 
Fixes https://github.com/adfinis-sygroup/timed-backend-static/issues/2
=> fix: use whitenoise middleware to host admin statics

timed/redmine/management/commands/redmine_report.py, timed/redmine/tests/test_redmine_report.py
total_hours was calculated for all reports during updated-range and not for total duration of the project
reverted the change in the command added in  #733
=> fix(redmine): fix total hours calculation

requirements-dev.txt, timed/permissions.py, timed/projects/models.py, timed/projects/tests/test_project.py, timed/tracking/serializers.py, timed/tracking/tests/snapshots/snap_test_report.py, timed/tracking/views.py
Use project's billed flag on new reports (e.g. when a project was paid in advance).
If a report is moved to a different project, task or customer, set the billed flag on the report according to the project the report was moved to.
Removed IsNotBilledOrVerified permission.
Tests for the billed flag are already implemented.
Following needs clarification with the admin:
=> fix(tracking): set correct value for billed flag on reports

timed/tracking/filters.py, timed/tracking/serializers.py, timed/tracking/tests/test_report.py
- Check if certain Report objects are from the same user
- Fix filtering of editable and non-editable reports for accountants
=> feat: include user in ReportIntersection

timed/tracking/filters.py
This is especially the case with projects that are billed in advance.
=> fix(filters): billing should not affect finish state of a report

timed/settings.py
This value should be customizable as there are big projects that have a lot of tasks, tasks and project assignees. In these cases the amount of fields exceeds the default value of 1000, which makes saving any changes on that project impossible.
I'll add the variable to our helm chart as well, so we can change it at any time.
=> feat(settings): add DATA_UPLOAD_MAX_NUMBER_FIELDS to env

timed/tracking/filters.py, timed/tracking/tests/test_report.py
only show reports in which user is responsible for reviewing
e.g. if user is project assignee with reviewer role, don't show
reports in which according task assignee with reviewer role is set
=> fix(tracking): update reviewer filter

requirements.txt, timed/settings.py
Customer Center needs to make requests to timed so we have to allow CORS from some domains that we can configure.
=> feat(settings): add CORS_ALLOWED_ORIGINS to env

timed/subscription/notify_admin.py
Using strptime throws an error if the passed date is over 23 hours.
So instead we use dateutils.parser. We also pass the day value to the mail template.
=> fix(subscriptions/notify_admin): use dateutils parser to prevent an error

timed/employment/filters.py
The date filter on the employments assumed that an unbounded employment
ends today, to simplify the generated SQL. However, this breaks when
the user is ahead of the server's timezone (for example, a user in
Australia requests his employment as of 2021-12-28, where in the server's
UTC timezone, it's still 2021-12-27 - the user won't receive an employment)
The filter now correctly checks that either the employment is ending
today or later, or is explicitly unbounded.
=> fix(filters): make date filter on employments work across timezones

timed/subscription/notify_admin.py, timed/subscription/tests/test_order.py, timed/subscription/views.py
notify only on orders created by customers
fix parser to correctly display purchased timed (for durations over 24h the parser didn't show correct numbers)
=> fix(subscription): fix parser and notifications for orders

.github/workflows/release.yaml
I also created #872 for tracking the fact that we should move to the new default anyway
=> chore(ci): fix building on legacy default branch

.github/workflows/release.yaml, CHANGELOG.md, CODEOWNERS, CONTRIBUTING.md, README.md
I wanted to touch the workflow since i just recently built it but decided it's simpler to do all of it in one go.
We want this fixed so the next release is published via CI. While GitHub did add a redirect to the container image registry, support for following such redirect is extremely spotty and pretty much a docker only feature.
=> chore: rename github orga from adfinis-sygroup to adfinis

timed/reports/filters.py, timed/reports/serializers.py, timed/reports/tests/test_customer_statistic.py, timed/reports/tests/test_project_statistic.py, timed/reports/tests/test_task_statistic.py, timed/reports/views.py
When filtering statistics, we face the problem that we want to
have a list of all tasks, and count the reported hours. Due to the
way Django works, the Sum of reported hours would trigger an (unfiltered)
subquery or Join, so our filters don't apply.
Therefore, we now have a "split" pseudo-queryset, which contains separate
querysets for tasks and reports. It then applies the filters to EITHER
of the querysets as needed (depending on prefix), then combines them
at the end of the filtering phase, using a subquery.
=> Filter stats

timed/tracking/serializers.py, timed/tracking/tests/test_report.py
Check if remaining effort tracking is active on the corresponding project when creating a new report as well.
Previously the check only worked when updating a report, but not when creating one (no instance when creating a new report).
=> fix(tracking): fix remaining effort check when creating report

timed/tracking/serializers.py, timed/tracking/tests/test_report.py
Just added missing field `rejected` to the Serializer
=> fix: add missing rejected field to ReportIntersectionSerializer

timed/tracking/models.py, timed/tracking/views.py
1. fix: move the PublicHoliday exclusion from absence object manager   
to AbsenceViewSet get_queryset()
2. fix: only exclude public holidays from the current employment.
This was an issue for users with multiple employments (past and current) at different locations,
as locations may have different public holidays.
=> fix(tracking): fix absence for users with multiple employments

timed/redmine/management/commands/import_project_data.py, timed/redmine/management/commands/update_project_expenditure.py, timed/redmine/tests/test_update_project_expenditure.py
Add pretend mode for update_project_expenditure and import_project_data commands so they can be tested without using productive data on test systems.
=> feat(redmine): add pretend mode to redmine commands

timed/projects/filters.py, timed/projects/tests/test_project.py, timed/projects/tests/test_task.py
We were in the need to pass multiple filter values for the `tasks` and `projects` endpoints. Further details regarding it's usage can be found here: https://github.com/adfinis/timed-frontend/pull/823
=> feat(filters): add number multi value filter

timed/reports/filters.py, timed/reports/tests/test_customer_statistic.py
The statistics should report zero hours instead of NULL. This makes the ordering of data actually work as expected
=> feat: empty sums in correcr ordering

timed/tracking/templates/mail/notify_user_rejected_reports.tmpl
This should make it easier for people receiving a mail about their reports being rejected to understand which action to take next.
=> chore(reject template): add further information to reject mail template

timed/redmine/management/commands/update_project_expenditure.py, timed/redmine/tests/test_update_project_expenditure.py
Write 0.00 in redmine if the project has no amount offered/invoiced and therefore no attribute `amount`
=> fix(redmine): fix NoneType for amount offered/invoiced for projects

timed/redmine/management/commands/import_project_data.py
Check if the `value` is empty, not if the `dict` is empty.
=> fix(redmine): fix value check for custom fields

Dockerfile
referencing master is a potential risk.
=> chore(dockerfile): pin wait-for-it version

timed/tracking/serializers.py, timed/tracking/tests/test_report.py, timed/tracking/views.py
Don't send emails when updating anything besides task on a rejected report that the user owns.
Updating the task on a rejected report should still automatically unreject the report.
Fixes #963
=> fix(tracking): don't send emails when updating own rejected reports

timed/redmine/management/commands/update_project_expenditure.py, timed/redmine/tests/test_update_project_expenditure.py
Decimal objects are not JSON serializable, therefore we have to convert them to float.
=> fix(redmine): convert Decimal objects to floats

.github/workflows/release.yaml, .github/workflows/schedule.yaml, .github/workflows/trivy-scan.yaml
chore(release): sign image using cosign
chore(release): create SBOM attestation and attach it to signed image
chore(trivy-scan): now has attest input
chore(schedule): now creates an attestation using cosign
=> code signing

timed/admin.py
we overlooked this when upgrading from 3.2 to 4.2, in the current state the admin page is just an error
=> fix(admin): fix admin page
