- timed/employment/admin.py
- timed/employment/factories.py
- timed/employment/models.py
- timed/employment/tests/test_employment.py
- timed/locale/en/LC_MESSAGES/django.po
- timed/settings.py
- timed/tracking/serializers.py
- timed/tracking/tests/test_activity_block.py
- timed/tracking/views.py
* Validate employments on model (only used in admin)
* Validate activity blocks on serializer
> Better validations

- .gitignore
- Makefile
- setup.py
This makes the timed-backend reusable by third party apps
> properly configure what packages are exposed

- timed/jsonapi_test_case.py
- timed/tracking/filters.py
- timed/tracking/permissions.py
- timed/tracking/tests/test_report.py
- timed/tracking/views.py
Broken backwards compatibility as reports are now not per default filtered
per user anymore. A user filter need to set manually to gain the same
behavior.
> Added additional filters to report end point

- .travis.yml
- dev_requirements.txt
- requirements.txt
- timed/tracking/tests/test_report.py
- timed/tracking/views.py
Additional endpoint supporting exporting of reports into csv, ods and xlsx.
> Add export functionality to reports endpoint

- timed/employment/serializers.py
- timed/employment/tests/test_user.py
- timed/tracking/tests/test_report.py
- timed/tracking/views.py
... and add ordering on reports
> Fix worktime balance for users without active employment

- timed/tracking/tests/test_report.py
If random duration of ReportFactory will have a duration of 1 hour this test would fail.
> Fix occasionally failing test

- timed/authentication.py
- timed/jsonapi_test_case.py
- timed/settings.py
This is mainly used in cases of file download.
> Allows json web token to be passed on as GET parameter

- timed/projects/admin.py
- timed/projects/models.py
- timed/projects/tests/test_project.py
When a new project gets added all tasks in task template will be added per default. Such can be removed later on when needed.
> Add template tasks to project per default.

- setup.py
This fixes issue management command notify_supervisors_shorttime and notify_reviewers_unverified not finding template.
> Include templates in python package

- timed/projects/admin.py
As default task were marked as not changed those were not saved when saving project.
> Default tasks need to be saved on new projects

- timed/projects/serializers.py
- timed/projects/tests/test_project.py
- timed/projects/views.py
Adds the possibility to view estimated and spent hours in frontend.
> Add spent hours onto project end point

- timed/projects/serializers.py
- timed/projects/tests/test_project.py
- timed/projects/views.py
Removing spent hours as it needs to be reworked as it is slow and returns invalid result per project.
Reverts adfinis-sygroup/timed-backend#73
> Revert "Add spent hours onto project end point"

- timed/settings.py
This simplifies containerization as it separates confidential data from unconfidential data.
> Split database url into different env vars

- timed/employment/filters.py
- timed/employment/serializers.py
- timed/employment/tests/test_user.py
- timed/employment/views.py
This PR is needed for frontend [PR #116](https://github.com/adfinis-sygroup/timed-frontend/pull/116) to work
> Add filters and fields for the user overview

- timed/settings.py
DEBUG flag was mistakenly set to True on production.
> Make default settings helper work with bools

- Makefile
- README.md
> Start only db with docker compose

- timed/employment/admin.py
- timed/employment/filters.py
- timed/employment/serializers.py
- timed/employment/tests/test_employment.py
- timed/employment/views.py
Superuser may only edit and supervisors by view employments of its supervisees.
> Expose employments to make it view- and editable by other users

- timed/permissions.py
- timed/tracking/filters.py
- timed/tracking/serializers.py
- timed/tracking/tests/test_absence.py
- timed/tracking/views.py
Changing of date, type or deleting of absence is not allowed though.
> Allow superuser and supervisor to access absences of other users

- timed/employment/models.py
- timed/employment/permissions.py
- timed/employment/serializers.py
- timed/employment/tests/test_user.py
- timed/employment/views.py
- timed/permissions.py
Superuser may additionally delete users without reports and create new ones.
> Allow superuser and supervisor to update user

- dev_requirements.txt
- timed/conftest.py
- timed/employment/tests/test_absence_type.py
- timed/employment/tests/test_location.py
- timed/employment/tests/test_public_holiday.py
- timed/jsonapi_test_case.py
- timed/projects/tests/test_customer.py
- timed/projects/tests/test_project.py
- timed/projects/tests/test_task.py
- timed/tests/client.py
- timed/tests/test_client.py
- timed/tracking/tests/test_activity.py
- timed/tracking/tests/test_activity_block.py
- timed/tracking/tests/test_attendance.py
- timed/tracking/tests/test_report.py
Converts all unit test to native pytest.
#128 needs to be merged first.
> Move to pytest

- timed/tracking/tests/test_report.py
- timed/tracking/views.py
This will be replaced in a future PR with bulk update
> Remove batch verify reports

- timed/mixins.py
- timed/serializers.py
- timed/tracking/serializers.py
- timed/tracking/tests/test_report.py
- timed/tracking/views.py
Returns a report-intersection resource with fields which are equal in result. If result has different values of one field None will be returned.
> Add report-intersection end point

- timed/tracking/filters.py
- timed/tracking/tests/test_report.py
Filters reports whether they are editable by user. Only owner, superuser, reviewers or supervisor may change a report.
> Add editable filter to report view

- timed/reports/tests/test_work_report.py
- timed/tracking/filters.py
- timed/tracking/serializers.py
- timed/tracking/tests/test_report.py
- timed/tracking/views.py
For better comprehensibility of bulk action this renames not_verified flag to verified.
> Add custom action to bulk update reports

- timed/tracking/filters.py
- timed/tracking/tests/test_report.py
- timed/tracking/views.py
This protects changing of reports which may already be billed.
> Enforce that only superuser may change verified reports

- timed/employment/filters.py
- timed/middleware.py
- timed/projects/filters.py
- timed/settings.py
- timed/tracking/filters.py
Updates of requirements caused those deprecation warnings which this PR fixes.
> Fix deprecation warnings

- timed/redmine/management/commands/redmine_report.py
This also logs Forbidden errors which up to now stopped process.
> Catch all redmine errors

- timed/tracking/views.py
This avoids duplicates during scrolling of reports
> Add missing id filter

- timed/subscription/filters.py
- timed/subscription/tests/test_package.py
previously the filter returned too many packages because of a JOIN
> fix package filter by replacing a JOIN with a subquery

- timed/employment/filters.py
- timed/employment/tests/test_user.py
The filter return users who are supervisors or not.
> Add is_supervisor filter

- .travis.yml
- Dockerfile
- requirements.txt
Extract uwsgi into requirements.txt so it is updated with pyup automatically
> Update docker python to 3.6 and uwsgi to 2.0.17

- timed/tracking/tests/test_report.py
- timed/tracking/views.py
Fixes issue that bulk changes get lost when making changes and verification in one go.
> Allow bulk verification and changes together

- .pre-commit-config.yaml
- CONTRIBUTING.md
- Dockerfile
- Makefile
- README.md
- docker-compose.override.yml
* Introduces pre-commit to simplify contribution
* Fixes docker container to install dev dependencies on dev machine
> Introduce contribution guidelines

- .isort.cfg
- requirements-dev.txt
- requirements.txt
- timed/conftest.py
- timed/permissions.py
- timed/projects/tests/test_task.py
- timed/projects/views.py
Any user that is a reviewer in at least on project is allowed to create,
update and delete tasks.
Some drive-by improvements for the testing setup using
pytest-factoryboy.
> feat(projects): make tasks modifiable for reviewers

- timed/reports/management/commands/notify_changed_employments.py
- timed/reports/management/commands/notify_reviewers_unverified.py
- timed/reports/management/commands/notify_supervisors_shorttime.py
- timed/settings.py
- timed/tracking/tasks.py
This should force servers to not reply with absence notices and related
stuff.
Resolves #476
> feat: set Auto-Submitted header in emails

- timed/forms.py
- timed/redmine/management/commands/redmine_report.py
- timed/reports/management/commands/notify_changed_employments.py
- timed/reports/management/commands/notify_reviewers_unverified.py
- timed/reports/management/commands/notify_supervisors_shorttime.py
- timed/settings.py
- timed/tracking/tasks.py
> Fix admin regressions

- pytest.ini
- timed/settings.py
> fix: replace deprecated pagination middleware

- timed/fixtures/test_data.json
The password now meets the Adsy policy
> fix(testdata): Update superuser password

- docker-compose.yml
> Match postgres version with production

- docker-compose.yml
Use correct path for keycloak config.
> fix: docker-compose setup

- cmd.sh
This reverts commit bae7f471d3f85d3e6a80ce4713825737979d007d.
> Fix uwsgi configuration

- uwsgi.ini
solves the problem of query-string limitations
> fix: increase uwsgi buffer-size

- CODEOWNERS
Let's see how this works out. This here is more of an experiment than
a production setting. If it gains traction, we'll add it to more projects
in the future
> feat: introduce code owners file

- docker-compose.yml
- timed/employment/models.py
> bump postgresql, typo

- README.md
- cmd.sh
Add documentation on the required steps to have a working development environment with the keycloak integration in place.
> 📝 readme: add steps to have a working development environment with users

- timed/employment/admin.py
- timed/locale/en/LC_MESSAGES/django.po
labels of foreign keys for the supervisor and supervisee inlines
needed to be changed
> fix: add custom forms for supervisor and supervisee inlines

- timed/redmine/templates/redmine/weekly_report.txt
- timed/redmine/tests/test_redmine_report.py
update formatting in weekly report template
> fix(redmine): update template formatting

- timed/fixtures/test_data.json
This will update the fixtures according to #772
> fix: update fixtures

- timed/permissions.py
- timed/tracking/views.py
rename permission to depict its functionality
> fix(permissions): rename IsNotBilledAndVerified permissions

- Makefile
- timed/fixtures/test_data.json
This will also add a command in Makefile which allows to start a
dbshell.
> fix(fixtures): add user with accountant role

- timed/employment/tests/test_user.py
- timed/employment/views.py
- timed/projects/tests/test_customer.py
- timed/projects/tests/test_project.py
- timed/projects/tests/test_task.py
- timed/projects/views.py
- timed/tracking/tests/test_report.py
- timed/tracking/views.py
update visibility in Report-, User-, Customer-, Project- and TaskViewSet
update employment check in ReportSerializer
> feat: update visibility to not depend on employment

- dev-config/keycloak-config.json
- timed/fixtures/test_data.json
This is especially need for the new customer-center changes
> fix: update fixtures and keycloak config

- timed/subscription/tests/test_subscription_project.py
- timed/subscription/views.py
Only show own (customer-visible) projects for customers
> fix(subscription): fix visibility on subscription-projects for customers

- timed/settings.py
- timed/subscription/notify_admin.py
- timed/subscription/serializers.py
- timed/subscription/templates/notify_accountants_order.html
- timed/subscription/templates/notify_accountants_order.txt
- timed/subscription/tests/test_order.py
- timed/subscription/views.py
moved acknowledged validation to OrderView
> Send mails on order creation

- timed/subscription/notify_admin.py
- fix(subscriptions/notify_admin): use dateutils parser to prevent an error
- fix(subscription/notify_admin): check project.estimate before calcualting total_hours
> fix mailing

- timed/conftest.py
- timed/employment/models.py
- timed/employment/tests/test_absence_type.py
- timed/employment/tests/test_location.py
- timed/employment/tests/test_public_holiday.py
- timed/employment/views.py
- timed/permissions.py
- timed/projects/factories.py
- timed/projects/tests/test_billing_type.py
- timed/projects/tests/test_cost_center.py
- timed/projects/tests/test_customer.py
- timed/projects/tests/test_customer_assignee.py
- timed/projects/tests/test_project.py
- timed/projects/tests/test_project_assignee.py
- timed/projects/tests/test_task.py
- timed/projects/tests/test_task_assignee.py
- timed/projects/views.py
- timed/reports/tests/test_customer_statistic.py
- timed/reports/tests/test_month_statistic.py
- timed/reports/tests/test_project_statistic.py
- timed/reports/tests/test_task_statistic.py
- timed/reports/tests/test_user_statistic.py
- timed/reports/tests/test_work_report.py
- timed/reports/tests/test_year_statistic.py
- timed/reports/views.py
- timed/subscription/views.py
Customers shouldn't be allowed to get all data from timed-backend.
Therefore I restricted the visibility on various models for customers.
> fix(visibility): restrict visibilty for customers

- timed/reports/management/commands/notify_reviewers_unverified.py
- timed/reports/tests/test_notify_reviewers_unverified.py
I used the same approach as in the reviewer filter for reports.
> fix(reports): add reviewer hierarchy in notify_reviewers_unverified

- timed/tracking/serializers.py
- timed/tracking/tests/test_report.py
updating billed reports should be allowed, as there are projects, that are billed in advance
> fix(tracking): allow updating billed reports

- .github/workflows/release.yaml
> chore(ci): publish container image to ghcr.io

- timed/employment/admin.py
- timed/projects/admin.py
add new user filter (internal employment)
> feat: add searchable dropdowns for user lists in admin

- Makefile
- poetry.lock
- pyproject.toml
- timed/settings.py
Added some commands to make the development of the app a little bit easier.
> chore: add Make commands for easier development

- timed/reports/serializers.py
- timed/reports/tests/test_customer_statistic.py
- timed/reports/tests/test_project_statistic.py
- timed/reports/views.py
fix ordering for project and customer statistics
include customer serializer for project statistics
add tests for filtering customer and project statistics
> fix(reports): fix project and customer statistics

- timed/reports/serializers.py
- timed/reports/tests/test_project_statistic.py
- timed/reports/tests/test_task_statistic.py
- timed/reports/views.py
add estimated_time field for task statistics
add estimated_time and total_remaining_effort for project statistics
> fix(statistics): add missing fields for project and task statistics

- .pre-commit-config.yaml
- timed/authentication.py
- timed/tests/test_authentication.py
> fix(auth): failing requests result in status_code 401

- timed/tracking/signals.py
- timed/tracking/tests/test_report.py
Change signal to pre_save and update most_recent_remaining_effort on task and total_remaining_effort on project if the value of remaining_effort on report has changed.
> fix(tracking): fix setting of remaining effort

- timed/tracking/signals.py
- timed/tracking/tests/test_report.py
update most_recent_remaining_effort on task and total_remaining_effort on project when creating a report
Fixes #933
> fix(tracking): fix remaining effort on report creation

- timed/tracking/tests/test_report.py
- timed/tracking/views.py
Send notifcations about rejected reports only if rejected is True
> fix(tracking): fix report update notifactions

- timed/redmine/management/commands/update_project_expenditure.py
Only added additional log statement
> fix(redmine): log estimated_hours in update_project_expenditure command
